apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-config              # Name of the ConfigMap
  namespace: pm               # Namespace where the config is stored
data:
  # Inference Service URLs
  INFERENCE_URL: http://inference:8000/predict        # Endpoint for sending prediction requests
  INFERENCE_HEALTH_URL: http://inference:8000/health  # Health check endpoint for inference service

  # Logger Service URLs
  LOGGER_URL: http://logger:8001/log                  # Endpoint to store request and prediction logs
  LOGGER_HEALTH_URL: http://logger:8001/health        # Health check endpoint for logger service

  # Batch Prediction Service URLs
  BATCH_PREDICT_URL: http://batch-predict:8002/predict-file   # Endpoint for batch dataset predictions
  BATCH_PREDICT_HEALTH_URL: http://batch-predict:8002/health  # Health check endpoint for batch service

  # Trainer Service URLs
  TRAINER_URL: http://trainer:8003/train              # Endpoint used to retrain the ML model
  TRAINER_HEALTH_URL: http://trainer:8003/health      # Health check endpoint for trainer service
