apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc                 # PVC name (used by inference/trainer to store the model)
  namespace: pm                   # Namespace where this PVC is created
spec:
  accessModes:
  - ReadWriteOnce                 # Can be mounted read-write by one node at a time
  resources:
    requests:
      storage: 1Gi                # Requested persistent storage size for model files
